In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

Reading the dataset

In [2]:
df= pd.read_csv('Mental Health Classification.csv')
df.head(5)

,Gender,Age,Education_Level,Employment_Status,Depression_Type,Symptoms,Low_Energy,Low_SelfEsteem,Search_Depression_Online,Worsening_Depression,...,How many times you eat,SocialMedia_Hours,SocialMedia_WhileEating,Sleep_Hours,Nervous_Level,Depression_Score,Coping_Methods,Self_Harm,Mental_Health_Support,Suicide_Attempts
0,1,25,2,3,5,11,1,1,1,1,...,0,10,3,10,10,10,11,0,0,0
1,1,25,2,2,5,0,1,1,0,1,...,0,8,3,4,10,10,0,0,1,0
2,1,25,2,3,2,5,1,1,1,1,...,0,10,3,4,10,10,0,1,1,1
3,0,25,2,2,6,7,0,1,0,1,...,0,4,3,3,10,10,5,1,1,1
4,1,25,2,2,6,5,0,0,0,0,...,1,3,3,7,1,3,0,0,0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1998 entries, 0 to 1997
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Gender                    1998 non-null   int64
 1   Age                       1998 non-null   int64
 2   Education_Level           1998 non-null   int64
 3   Employment_Status         1998 non-null   int64
 4   Depression_Type           1998 non-null   int64
 5   Symptoms                  1998 non-null   int64
 6   Low_Energy                1998 non-null   int64
 7   Low_SelfEsteem            1998 non-null   int64
 8   Search_Depression_Online  1998 non-null   int64
 9   Worsening_Depression      1998 non-null   int64
 10  Your overeating level     1998 non-null   int64
 11  How many times you eat    1998 non-null   int64
 12  SocialMedia_Hours         1998 non-null   int64
 13  SocialMedia_WhileEating   1998 non-null   int64
 14  Sleep_Hours               1998 non-null   int64
 15  Nervous_Level             1998 non-null   int64
 16  Depression_Score          1998 non-null   int64
 17  Coping_Methods            1998 non-null   int64
 18  Self_Harm                 1998 non-null   int64
 19  Mental_Health_Support     1998 non-null   int64
 20  Suicide_Attempts          1998 non-null   int64
dtypes: int64(21)
memory usage: 327.9 KB

In [4]:
df.describe()

,Gender,Age,Education_Level,Employment_Status,Depression_Type,Symptoms,Low_Energy,Low_SelfEsteem,Search_Depression_Online,Worsening_Depression,...,How many times you eat,SocialMedia_Hours,SocialMedia_WhileEating,Sleep_Hours,Nervous_Level,Depression_Score,Coping_Methods,Self_Harm,Mental_Health_Support,Suicide_Attempts
count,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,...,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000,1998.000000
mean,0.514014,24.261762,1.869369,2.097097,5.673173,6.553053,0.709710,0.696196,0.386887,0.652152,...,0.204705,5.960961,2.063564,6.505506,5.702202,14.622623,5.920420,0.098098,0.224725,1.434434
std,0.499929,7.928578,0.472003,0.873915,2.935595,3.852428,0.485973,0.488522,0.487159,0.476407,...,0.403587,3.728180,0.992946,2.278048,2.504859,8.948343,4.092346,0.297522,0.417505,1.135513
min,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,25.000000,2.000000,2.000000,2.000000,5.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,3.000000,2.000000,5.000000,4.000000,7.000000,2.000000,0.000000,0.000000,0.000000
50%,1.000000,25.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,0.000000,1.000000,...,0.000000,6.000000,2.000000,7.000000,5.000000,14.000000,6.000000,0.000000,0.000000,1.000000
75%,1.000000,25.000000,2.000000,2.000000,9.000000,9.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,9.000000,3.000000,8.000000,8.000000,22.000000,9.000000,0.000000,0.000000,2.000000
max,1.000000,35.000000,3.000000,4.000000,11.000000,14.000000,2.000000,2.000000,1.000000,1.000000,...,1.000000,12.000000,3.000000,10.000000,10.000000,30.000000,13.000000,1.000000,1.000000,3.000000

In [5]:
df.corr()

,Gender,Age,Education_Level,Employment_Status,Depression_Type,Symptoms,Low_Energy,Low_SelfEsteem,Search_Depression_Online,Worsening_Depression,...,How many times you eat,SocialMedia_Hours,SocialMedia_WhileEating,Sleep_Hours,Nervous_Level,Depression_Score,Coping_Methods,Self_Harm,Mental_Health_Support,Suicide_Attempts
Gender,1.000000,0.011771,0.000335,0.028976,0.015918,0.007024,-0.005919,-0.049195,-0.047974,-0.035238,...,-0.017948,-0.030335,-0.004317,-0.021173,-0.005263,-0.028928,0.019759,0.010952,0.010095,0.034257
Age,0.011771,1.000000,-0.013070,0.013241,0.025343,0.005668,-0.031604,0.009294,-0.001859,-0.017642,...,-0.006739,0.028078,0.005327,0.000988,0.004053,-0.017798,-0.010454,-0.025538,-0.010367,-0.003571
Education_Level,0.000335,-0.013070,1.000000,0.069612,0.017599,-0.048373,-0.016953,-0.080988,-0.039248,-0.155411,...,-0.061964,0.011044,0.013452,-0.052189,0.018329,0.022112,0.043612,-0.186836,-0.122852,-0.012718
Employment_Status,0.028976,0.013241,0.069612,1.000000,0.105872,0.006203,-0.064476,0.009311,-0.057700,0.046285,...,-0.056383,0.023911,0.024623,0.017087,0.034032,-0.041673,0.007202,-0.117540,-0.190214,-0.028400
Depression_Type,0.015918,0.025343,0.017599,0.105872,1.000000,-0.132253,-0.189388,-0.164944,0.066752,0.024654,...,0.122432,0.015763,0.062963,0.039918,-0.086518,-0.022559,0.017675,-0.143300,0.031764,0.036156
Symptoms,0.007024,0.005668,-0.048373,0.006203,-0.132253,1.000000,-0.092338,0.057925,-0.058303,-0.037278,...,-0.105703,0.026956,-0.036947,-0.038548,0.125168,-0.024069,-0.127656,0.195551,0.342989,0.008923
Low_Energy,-0.005919,-0.031604,-0.016953,-0.064476,-0.189388,-0.092338,1.000000,0.086044,0.062173,0.180056,...,-0.148774,-0.015931,-0.044760,-0.016648,0.124346,-0.016913,0.105712,0.003106,-0.142305,0.018123
Low_SelfEsteem,-0.049195,0.009294,-0.080988,0.009311,-0.164944,0.057925,0.086044,1.000000,0.165888,0.490254,...,-0.055226,0.014655,0.049121,-0.002771,0.398266,-0.013983,-0.095758,0.012215,-0.114390,-0.017421
Search_Depression_Online,-0.047974,-0.001859,-0.039248,-0.057700,0.066752,-0.058303,0.062173,0.165888,1.000000,0.042907,...,0.106367,0.000049,0.052656,-0.003500,0.011161,0.012947,0.142797,0.007498,-0.169170,-0.003456
Worsening_Depression,-0.035238,-0.017642,-0.155411,0.046285,0.024654,-0.037278,0.180056,0.490254,0.042907,1.000000,...,0.133527,-0.012160,0.095458,-0.004925,0.563988,-0.012836,-0.080985,0.240863,-0.039819,0.001788
Your overeating level,-0.029479,-0.001370,-0.052821,0.087203,-0.056730,-0.022716,-0.123446,0.055413,-0.052573,0.207850,...,0.195914,-0.001693,0.045377,0.005723,0.042946,0.022268,-0.118441,-0.062800,-0.158669,-0.006563
How many times you eat,-0.017948,-0.006739,-0.061964,-0.056383,0.122432,-0.105703,-0.148774,-0.055226,0.106367,0.133527,...,1.000000,-0.037618,0.129958,-0.026008,0.141567,0.025422,0.068384,0.057875,-0.112669,-0.021508
SocialMedia_Hours,-0.030335,0.028078,0.011044,0.023911,0.015763,0.026956,-0.015931,0.014655,0.000049,-0.012160,...,-0.037618,1.000000,-0.047756,0.003799,-0.001246,0.019927,-0.004339,-0.023632,0.009500,0.003772
SocialMedia_WhileEating,-0.004317,0.005327,0.013452,0.024623,0.062963,-0.036947,-0.044760,0.049121,0.052656,0.095458,...,0.129958,-0.047756,1.000000,0.013681,0.066605,0.016001,0.015047,0.178896,0.039209,-0.031610
Sleep_Hours,-0.021173,0.000988,-0.052189,0.017087,0.039918,-0.038548,-0.016648,-0.002771,-0.003500,-0.004925,...,-0.026008,0.003799,0.013681,1.000000,-0.032665,-0.023235,0.004371,0.026539,0.015283,-0.028027
Nervous_Level,-0.005263,0.004053,0.018329,0.034032,-0.086518,0.125168,0.124346,0.398266,0.011161,0.563988,...,0.141567,-0.001246,0.066605,-0.032665,1.000000,0.000368,-0.027129,0.259610,0.024282,-0.003435
Depression_Score,-0.028928,-0.017798,0.022112,-0.041673,-0.022559,-0.024069,-0.016913,-0.013983,0.012947,-0.012836,...,0.025422,0.019927,0.016001,-0.023235,0.000368,1.000000,0.014891,-0.033674,-0.030635,0.019543
Coping_Methods,0.019759,-0.010454,0.043612,0.007202,0.017675,-0.127656,0.105712,-0.095758,0.142797,-0.080985,...,0.068384,-0.004339,0.015047,0.004371,-0.027129,0.014891,1.000000,0.003125,-0.131672,-0.020359
Self_Harm,0.010952,-0.025538,-0.186836,-0.117540,-0.143300,0.195551,0.003106,0.012215,0.007498,0.240863,...,0.057875,-0.023632,0.178896,0.026539,0.259610,-0.033674,0.003125,1.000000,0.370691,-0.022454
Mental_Health_Support,0.010095,-0.010367,-0.122852,-0.190214,0.031764,0.342989,-0.142305,-0.114390,-0.169170,-0.039819,...,-0.112669,0.009500,0.039209,0.015283,0.024282,-0.030635,-0.131672,0.370691,1.000000,0.010498
Suicide_Attempts,0.034257,-0.003571,-0.012718,-0.028400,0.036156,0.008923,0.018123,-0.017421,-0.003456,0.001788,...,-0.021508,0.003772,-0.031610,-0.028027,-0.003435,0.019543,-0.020359,-0.022454,0.010498,1.000000

In [6]:
df['Depression_Type'].value_counts()

Depression_Type
9     627
2     449
5     386
6     193
4     131
11     34
1      33
0      32
7      32
3      31
10     29
8      21
Name: count, dtype: int64

Feature Selection Using SelectKBest

In [10]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [13]:
for i, col in enumerate(df.columns):
    print(i, col)

0 Gender
1 Age
2 Education_Level
3 Employment_Status
4 Depression_Type
5 Symptoms
6 Low_Energy
7 Low_SelfEsteem
8 Search_Depression_Online
9 Worsening_Depression
10 Your overeating level
11 How many times you eat
12 SocialMedia_Hours
13 SocialMedia_WhileEating
14 Sleep_Hours
15 Nervous_Level
16 Depression_Score
17 Coping_Methods
18 Self_Harm
19 Mental_Health_Support
20 Suicide_Attempts

In [15]:
X= df.iloc[:,0:21]   #all features
Y= df.iloc[:,4]   #target output (Depression_Type)

In [16]:
best_features= SelectKBest(score_func=chi2, k=3)
fit= best_features.fit(X,Y)

In [17]:
df_scores= pd.DataFrame(fit.scores_)
df_columns= pd.DataFrame(X.columns)

In [19]:
features_scores = pd.concat([df_columns, df_scores], axis=1)
features_scores.columns = ['Features', 'Score']

features_scores = features_scores.sort_values(by='Score', ascending=False)
features_scores['Rank'] = range(1, len(features_scores) + 1)

features_scores

                    Features        Score  Rank
4            Depression_Type  3033.501985     1
5                   Symptoms  1053.096142     2
17            Coping_Methods   584.326335     3
15             Nervous_Level   363.465947     4
11   How many times you eat    361.716808     5
19     Mental_Health_Support   326.387696     6
10     Your overeating level   301.527887     7
8   Search_Depression_Online   216.061913     8
18                 Self_Harm   210.834190     9
13   SocialMedia_WhileEating   150.616070    10
6                 Low_Energy   108.186123    11
3          Employment_Status   106.506811    12
16          Depression_Score   105.102278    13
9       Worsening_Depression   103.976701    14
7             Low_SelfEsteem    99.605017    15
2            Education_Level    51.522468    16
12         SocialMedia_Hours    22.561754    17
1                        Age    19.075906    18
20          Suicide_Attempts    16.559871    19
14               Sleep_Hours    11.667221    20
0                     Gender     4.976869    21

Cross-Tab

In [ ]:
X = df.iloc[:, [9, 6, 7]]   # SEP, JUN, JUL
Y = df.iloc[:, [14]]        # FLOODS

In [34]:
for col in df.columns:
    if col != 'Depression_Type':
        print(f"\nChecking: {col}")
        print(pd.crosstab(df[col], df['Depression_Type']))

Checking: Gender
Depression_Type  0   1    2   3   4    5    6   7   8    9   10  11
Gender
0                16  18  217  16  71  187   92  15   5  309  10  15
1                16  15  232  15  60  199  101  17  16  318  19  19

Checking: Age
Depression_Type  0   1    2   3   4    5    6   7   8    9   10  11
Age
10                8   4   96   5  24   71   32   5   4  113   9   6
25               18  22  262  21  80  233  125  21  11  377  16  17
35                6   7   91   5  27   82   36   6   6  137   4  11

Checking: Education_Level
Depression_Type  0   1    2   3   4    5    6   7   8    9   10  11
Education_Level
0                 0   0    0   0  23   24   30   0   0    0   0   0
1                 0   0   27   0  29   30    0  32  21    0   0   0
2                32  33  390  31  79  332  163   0   0  627  29  34
3                 0   0   32   0   0    0    0   0   0    0   0   0

Checking: Employment_Status
Depression_Type    0   1    2   3    4    5    6   7   8    9   10  11
Employment_Status
0                   0   0   59   0    0   88    0   0   0    0   0   0
1                   0   0    0  31    0    0   30   0   0    0   0   0
2                  32  33  256   0  108  268  163   0  21  470  29  34
3                   0   0   38   0   23   30    0  32   0   80   0   0
4                   0   0   96   0    0    0    0   0   0   77   0   0

Checking: Symptoms
Depression_Type  0   1    2   3   4    5   6   7   8    9   10  11
Symptoms
0                 0   0    0   0   0   29   0   0   0   23   0   0
1                32   0    0   0  23   28   0   0   0   53   0   0
2                 0   0    0   0   0    0   0   0   0   38   0   0
3                 0   0   42   0  29    0   0   0   0   47   0   0
4                 0   0    0   0   0    0   0   0   0    0  29   0
5                 0   0  229  31  29  175  95   0   0  342   0   0
6                 0   0    0   0  20    0   0   0   0    0   0   0
7                 0   0   32   0   0    0  32   0   0   59   0   0
8                 0   0    0   0   0   30   0   0  21    0   0   0
9                 0   0    0   0   0   38   0   0   0    0   0   0
10                0   0    0   0   0    0   0  32   0    0   0   0
11                0   0    0   0   0   30   0   0   0   33   0   0
12                0  33    0   0   0    0   0   0   0    0   0   0
13                0   0  146   0  30   56  66   0   0   32   0   0
14                0   0    0   0   0    0   0   0   0    0   0  34

Checking: Low_Energy
Depression_Type  0   1    2   3    4    5    6   7   8    9   10  11
Low_Energy
0                 0   0   79   0    0  148  106  32  21  190   0  34
1                32  33  370  31  131  238   57   0   0  437  29   0
2                 0   0    0   0    0    0   30   0   0    0   0   0

Checking: Low_SelfEsteem
Depression_Type  0   1    2   3    4    5    6   7   8    9   10  11
Low_SelfEsteem
0                 0   0  150   0   29  112   35  32  21  192  29  34
1                32  33  272  31  102  274  158   0   0  435   0   0
2                 0   0   27   0    0    0    0   0   0    0   0   0

Checking: Search_Depression_Online
Depression_Type           0   1    2   3    4    5    6   7   8    9   10  11
Search_Depression_Online
0                         32  33  316  31   23  181  163  32  21  330  29  34
1                          0   0  133   0  108  205   30   0   0  297   0   0

Checking: Worsening_Depression
Depression_Type       0   1    2   3    4    5    6   7   8    9   10  11
Worsening_Depression
0                      0   0  219   0   29  116   74  32  21  170   0  34
1                     32  33  230  31  102  270  119   0   0  457  29   0

Checking: Your overeating level
Depression_Type        0   1    2   3   4    5   6   7   8    9   10  11
Your overeating level
0                       0   0   71   0  29    0   0   0  21  105   0   0
1                       0   0    0   0  20    0   0   0   0    0   0   0
2                       0   0    0   0   0    0  32   0   0    0   0   0
3                       0   0    0   0   0   29   0   0   0    0   0   0
4                       0   0   50   0   0   59   0   0   0    0   0   0
5                       0   0    0   0   0   28   0   0   0   61   0   0
6                       0   0    0   0   0    0  39   0   0    0   0   0
7                       0  33   32   0  23   30   0   0   0   61   0   0
8                       0   0   58   0   0  156  95  32   0  173  29  34
9                       0   0  158  31   0   24   0   0   0  103   0   0
10                      0   0   52   0   0    0  27   0   0   55   0   0
11                      0   0   28   0  59   60   0   0   0   69   0   0
12                     32   0    0   0   0    0   0   0   0    0   0   0

Checking: How many times you eat
Depression_Type          0   1    2   3   4    5    6   7   8    9   10  11
How many times you eat
0                         0  33  449  31  72  283  158  32  21  476   0  34
1                        32   0    0   0  59  103   35   0   0  151  29   0

Checking: SocialMedia_Hours
Depression_Type    0   1   2   3   4   5   6   7   8   9   10  11
SocialMedia_Hours
0                   3   6  34   3  11  22  17   2   3  48   5   1
1                   1   3  35   4  13  45  16   1   0  51   5   0
2                   2   4  31   0   6  27  12   3   1  42   2   6
3                   6   1  29   1  13  20  19   3   4  50   1   1
4                   3   1  43   2   8  30  12   0   2  45   1   5
5                   2   1  36   4  14  28  21   3   2  46   2   3
6                   5   3  27   1   8  34  15   4   1  50   3   3
7                   2   1  43   2   7  28  22   0   1  45   1   0
8                   4   1  36   6   9  27   9   4   0  48   1   1
9                   1   4  31   2   8  38  16   4   2  60   2   1
10                  1   4  40   2  17  32   9   2   3  44   1   5
11                  1   2  38   3   7  24  14   3   1  56   4   2
12                  1   2  26   1  10  31  11   3   1  42   1   6

Checking: SocialMedia_WhileEating
Depression_Type          0   1    2   3   4    5    6   7   8    9   10  11
SocialMedia_WhileEating
0                         0   0   61   0  23   70    0   0   0   70   0   0
1                         0   0   59  31  20   81    0   0   0   62   0   0
2                         0   0  197   0  30  116   30  32   0  254   0  34
3                        32  33  132   0  58  119  163   0  21  241  29   0

Checking: Sleep_Hours
Depression_Type  0   1   2   3   4   5   6   7   8   9   10  11
Sleep_Hours
3                 4   5  55   4  12  61  23   3   1  60   4   5
4                 4   4  63   7  14  42  29   1   4  83   7   4
5                 2   3  72   4  16  53  24   7   0  71   1   6
6                 5   6  54   3  13  38  15   3   1  80   4   4
7                 6   3  45   2  24  51  25   3   5  87   1   4
8                 3   5  63   8  14  42  23   2   5  93   6   5
9                 3   2  53   2  18  54  26   6   3  72   2   5
10                5   5  44   1  20  45  28   7   2  81   4   1

Checking: Nervous_Level
Depression_Type  0   1    2   3   4    5   6   7   8    9   10  11
Nervous_Level
1                 0   0    0   0  29    0  74   0   0   34   0   0
2                 0   0   69   0   0    0   0   0   0   25   0   0
3                 0   0    0   0   0   28   0  32   0   38   0   0
4                 0   0   33   0   0   66   0   0   0   93   0  34
5                 0   0  238   0  23  104  30   0   0  154   0   0
6                 0   0   30   0   0   30   0   0  21   92   0   0
7                 0   0   61   0   0   29  30   0   0   95   0   0
8                 0  33    0  31  29   38  27   0   0   52  29   0
10               32   0   18   0  50   91  32   0   0   44   0   0

Checking: Depression_Score
Depression_Type   0   1   2   3   4   5   6   7   8   9   10  11
Depression_Score
0                  0   0  10   0   6  11  10   1   1  22   0   0
1                  0   1  15   1   3  14   8   1   0  15   1   3
2                  1   0  16   2   5  13   7   1   1  22   1   0
3                  0   1  11   0   5  16   6   2   1  28   0   2
4                  0   0   9   0   5  15   7   2   1  21   0   0
5                  2   0  17   1   6  12   6   0   0  27   1   0
6                  0   1  17   2   5  14   7   0   0  24   1   0
7                  1   3  22   2   4  13  11   1   0  23   2   2
8                  1   1  13   2   4   8  10   1   2  26   0   1
9                  2   3  14   2   4  12   5   1   1  28   1   0
10                 2   3  19   2   3  13   8   2   1  14   0   3
11                 0   1  12   0   4  13   5   1   0  22   0   2
12                 0   0  13   2   6  11   3   1   2  21   0   1
13                 1   2  17   1   3  15   5   2   0  23   0   1
14                 1   0  20   1   1  13   4   2   2  23   0   1
15                 2   0  13   0   7   7   3   1   0  21   0   1
16                 0   0  21   4   9  19   3   0   2  10   1   0
17                 0   2  12   2   1  13  12   1   1  14   2   0
18                 3   0  11   0   3  15   7   1   0  19   2   2
19                 1   0  14   1   4  12   4   3   0  21   2   1
20                 1   2  13   1   4   9   3   1   0  24   1   0
21                 1   0  17   0   8  10   5   2   1  15   0   0
22                 3   2  17   0   3   7   4   0   0  21   0   2
23                 1   0  11   0   5  14   7   0   1  20   3   0
24                 0   2  14   1   2  13   7   1   2  13   1   1
25                 1   4  12   0   3  11   5   0   0  18   1   2
26                 1   1  14   2   3  14   7   0   1  17   1   1
27                 2   2  11   0   6   8   9   1   0  17   2   0
28                 1   1  13   0   4  14   4   0   1  18   1   2
29                 2   0  12   0   1  15   4   2   0  20   1   4
30                 2   1  19   2   4  12   7   1   0  20   4   2

Checking: Coping_Methods
Depression_Type  0   1    2   3   4    5   6   7   8    9   10  11
Coping_Methods
0                 0   0  136   0   0   59  35   0   0   28   0   0
1                 0   0    0   0   0   29   0   0   0    0   0   0
2                 0   0    0  31   0  104  66   0   0  119   0  34
3                 0   0   55   0  29    0   0   0   0   94   0   0
4                 0   0    0   0   0    0   0   0   0   38  29   0
5                 0   0    0   0   0   24  32   0   0    0   0   0
6                 0  33    0   0   0   32   0   0   0    0   0   0
7                 0   0    0   0  23   28   0  32   0    0   0   0
8                 0   0   37   0   0    0   0   0   0    0   0   0
9                32   0  127   0  79   24  30   0   0  169   0   0
10                0   0    0   0   0   30   0   0   0   49   0   0
11                0   0   74   0   0   30  30   0   0  105   0   0
12                0   0    0   0   0    0   0   0  21    0   0   0
13                0   0   20   0   0   26   0   0   0   25   0   0

Checking: Self_Harm
Depression_Type  0   1    2   3    4    5    6   7   8    9   10  11
Self_Harm
0                32  33  399  31  101  332  131  32  21  627  29  34
1                 0   0   50   0   30   54   62   0   0    0   0   0

Checking: Mental_Health_Support
Depression_Type        0   1    2   3    4    5    6   7   8    9   10  11
Mental_Health_Support
0                      32  33  372   0  101  303  122   0  21  536  29   0
1                       0   0   77  31   30   83   71  32   0   91   0  34

Checking: Suicide_Attempts
Depression_Type   0   1    2   3   4    5   6   7   8    9   10  11
Suicide_Attempts
0                 14   7  139   7  46   86  57   7   4  173   8  11
1                  8   5  122   6  32  102  45   7   7  150   5   6
2                  8  14   78  10  26  104  37   7   6  153   8  10
3                  2   7  110   8  27   94  54  11   4  151   8   7

In [35]:
for col in df.columns:
    if col != 'Depression_Type':
        grouped = df.groupby(col)['Depression_Type'].nunique()
        if any(grouped == 1):
            print(f"Possible leakage in: {col}")

Possible leakage in: Education_Level
Possible leakage in: Symptoms
Possible leakage in: Low_Energy
Possible leakage in: Low_SelfEsteem
Possible leakage in: Your overeating level
Possible leakage in: Coping_Methods

In [36]:
df.corr()['Depression_Type'].sort_values(ascending=False)

Depression_Type             1.000000
How many times you eat      0.122432
Employment_Status           0.105872
Search_Depression_Online    0.066752
SocialMedia_WhileEating     0.062963
Sleep_Hours                 0.039918
Suicide_Attempts            0.036156
Mental_Health_Support       0.031764
Age                         0.025343
Worsening_Depression        0.024654
Coping_Methods              0.017675
Education_Level             0.017599
Gender                      0.015918
SocialMedia_Hours           0.015763
Depression_Score           -0.022559
Your overeating level      -0.056730
Nervous_Level              -0.086518
Symptoms                   -0.132253
Self_Harm                  -0.143300
Low_SelfEsteem             -0.164944
Low_Energy                 -0.189388
Name: Depression_Type, dtype: float64